### PR TITLE
CLI-1377 Delay API lookup of application by ID

### PR DESCRIPTION
**Pull request by mglaman**
**Motivation**
Fixes CLI-1377

**Proposed changes**
We are passing destination URLs and other required parameters to an application which isn't accessible over the API and doesn't need to be given the provided params

**Alternatives considered**
Fake the ID

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built acli.phar](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#automatic-dev-builds) for this PR.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. (add specific steps for this pr)

### CODE REVIEW

**Comment by danepowell** [comment]
@mglaman are you able to fix the test cases for this?

**Comment by mglaman** [comment]
@danepowell yeah, it fell off my radar, thanks for the ping!

**Comment by mglaman** [comment]
sorry for commit spam, couldn't run tests locally

**Review by danepowell — APPROVED** [review]

**Comment by danepowell** [comment]
Thanks for the PR!

**Pull request merged**
