### PR TITLE
Bold values in output text.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by anavarre** [comment]
This still doesn't render great here

acli-sitegroup-link

**Comment by grasmash** [comment]
Yeah, I know. What do you suggest? Feel free to play around with it.

**Comment by anavarre** [comment]
I would keep it simple like so:

- Same background for consistency
- Text in bold and/or different color to indicate this is a computed variable

question-output-suggestion

Example like so:

```
$question = new ConfirmationQuestion("<question>Would you like to link the Cloud application <bg=cyan; options=bold>{$cloud_application->name}</> to this repository</question>? ");
```

**Comment by grasmash** [comment]
@anavarre Is it working for you now?

**Comment by anavarre** [comment]
Working now!

**Pull request merged**
