### PR TITLE
#Fixes: 468: Users get confused because there's no visible output when entering their API secret.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by anavarre** [comment]
Alternatively, if we can use *************** perhaps it's best.

**Comment by grasmash** [comment]
Not sure how much we can really change here, we're relying on Symfony's internal input handling: https://symfony.com/doc/current/components/console/helpers/questionhelper.html#hiding-the-user-s-response

**Comment by grasmash** [comment]
Yeah, I don't know what we can do about this: https://github.com/symfony/console/blob/5.x/Helper/QuestionHelper.php#L432

**Comment by grasmash** [comment]
IMO, this is not worth the effort to change. We can either accept the change proposed here or un-hide the input.

**Comment by anavarre** [comment]
I'd say let's go with your initial suggestion, then.

**Comment by anavarre** [comment]
Is this the expected theming?

470-theming

I feel we should have consistency for questions.

**Comment by grasmash** [comment]
Hmmm. Looks like we did this differently for a reason: Windows compatibility.

**Comment by grasmash** [comment]
image

**Review by anavarre — APPROVED** [review]
Looks good. Like how it's consistent now. FYI the key icon looks great but it doesn't work on Linux.

**Pull request merged**
