### PR TITLE
Fixes CLI-652: Support xDebug for PHP 8.

### PR DESCRIPTION
**Pull request by grasmash**
**Motivation**

Fixes #NNN

**Proposed changes**

**Alternatives considered**

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. (add specific steps for this pr)

**Merge requirements**
- [ ] _Bug_, _enhancement_, or _breaking change_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by anavarre** [comment]
@grasmash @danepowell which Cloud IDE behavior would you like ultimately?

`xdebug.ini` is the file that loads the Xdebug configuration, and when we switch to PHP 8.0 we rename `xdebug.ini` to `xdebug2.ini` and `xdebug3.ini` to `xdebug.ini`. Vice versa when we switch back to PHP 7.4

```ide:~/configs/php $ tree
.
├── custom.ini
├── xdebug3.ini
└── xdebug.ini

0 directories, 3 files
```

Or, `xdebug.ini`'s behavior remains the same, but we always copy either `xdebug3.ini` or `xdebug2.ini` into `xdebug.ini` as we change PHP versions.

```
ide:~/configs/php $ tree
.
├── custom.ini
├── xdebug3.ini
├── xdebug2.ini
└── xdebug.ini

0 directories, 3 files
```

I suspect the later is what you expect and want to make sure we get the ball rolling on this one.

**Comment by danepowell** [comment]
We should have separate configuration directories per version of PHP, i.e. `~/configs/php/7.4` and `~/configs/php/8.0`. This is standard across pretty much every distributed version of PHP (brew, apt, snap, etc). Also the base filename shouldn't matter, any `*.ini` file should be globbed.

Is that too much to ask in a PR comment? 😁 If so I prefer Aurelien's option 2.

**Comment by anavarre** [comment]
> We should have separate configuration directories per version of PHP

Why not, though it's only going to be needed until PHP 7.4 is EOL'ed. PHP 8+ all need Xdebug 3.

**Comment by anavarre** [comment]
If my understanding is correct and I need to have both `xdebug2.ini` and `xdebug3.ini` files standing by, what I expect is that whichever PHP version I'm on and whichever content there is within `xdebug.ini`, upon typing `acli xdebug` I should have the file copied over. That's not the case ATM:

```
test:~/configs/php $ cat xdebug2.ini 
; Acquia Hosting XDebug defaults
; This file configures the default settings for xdebug.
[xdebug]
;zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_port=9001
xdebug.auto_trace=Off
xdebug.default_enable=Off
xdebug.max_nesting_level=2000
xdebug.profiler_enable=Off
test:~/configs/php $ cat xdebug3.ini 
; Acquia Hosting XDebug defaults
; This file configures the default settings for xdebug.
[xdebug]
;zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=localhost
xdebug.client_port=9001
xdebug.max_nesting_level=2000
test:~/configs/php $ php -v
PHP 7.4.26 (cli) (built: Dec  1 2021 11:08:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
test:~/configs/php $ ./acli.phar xdebug
Xdebug PHP extension disabled.
test:~/configs/php $ cat xdebug.ini 
; Acquia Hosting XDebug defaults
; This file configures the default settings for xdebug.
[xdebug]
;zend_extension=xdebug.so
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=localhost
xdebug.client_port=9001
xdebug.max_nesting_level=2000
```

**Comment by anavarre** [comment]
Dane and I have manually tested this and Symfony required `TRUE` to be passed to getFilesystem()->copy() so the file would be copied in place upon switching PHP versions (see [511b81f](https://github.com/acquia/cli/pull/839/commits/511b81f5e6a8b447b36c53c358d92b1980dab359))

**Comment by grasmash** [comment]
Thank you! It was so close.

**Pull request merged**
