### PR TITLE
CLI-864 | Unhide cs:wizard from list of ACLI commands

### LINKED ISSUE #1192: CLI-864: Unhide cs:wizard from list of ACLI commands
Code Studio can be set up and used in a local development environment, so the cs:wizard command no longer has to be restricted to the Cloud IDE acli command list.

### PR DESCRIPTION
**Pull request by klaw772**
**Motivation**
Fixes #1192 

**Proposed changes**
Shows cs:wizard in the acli command list.

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#building-and-testing) to set up your development environment or [download a pre-built acli.phar](https://github.com/acquia/cli/blob/HEAD/CONTRIBUTING.md#automatic-dev-builds) for this PR.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. Run `./bin/acli` and see `codestudio:wizard` in the list of available commands.

### CODE REVIEW

**Comment by anavarre** [comment]
Do we really want that? 

```
❯ acli cs:wizard

In CodeStudioCommandTrait.php line 94:

  Could not determine GitLab host: sh: line 0: exec: glab: not found


codestudio:wizard [--key KEY] [--secret SECRET] [--gitlab-token GITLAB-TOKEN] [--gitlab-project-id GITLAB-PROJECT-ID] [--gitlab-host-name GITLAB-HOST-NAME] [--] [<applicationUuid>]
```

We don't yet have a great user journey to guide users into setting things up.

**Comment by klaw772** [comment]
@anavarre That's a good point - I'm planning on exploring how to more seamlessly work in the glab auth process. In the meantime, should I close this PR until then?

**Comment by anavarre** [comment]
Maybe let's ask @danepowell what he thinks of that before we close it out?

**Comment by danepowell** [comment]
Is there just a dependency on the glab binary being present? If so we have methods (I think in LocalMachineHelper) that can check that a binary exists, we already do this for composer and Git.

As long as this throws user-friendly errors ("here's how to set up glab auth") rather than hostile warnings, I'm happy.

**Comment by joshirohit100** [comment]
This was added in https://github.com/acquia/cli/pull/873.
For local, if we run `acli cs:wizard --gitlab-host-name=code.acquia.com --gitlab-token=<TOKEN_HERE>`, we don;t need GLAB dependency.

**Comment by klaw772** [comment]
@joshirohit100 that's a good point, but I'm not sure if it's feasible to assume that the user will always include the host name and token as options. I'm adding in a quick check when verifying the GitLab host that the 'glab' command exists and showing a friendlier message if it doesn't.

**Comment by danepowell** [comment]
Thanks for the PR and fixing up tests!

**Comment by danepowell** [comment]
Sorry, Coveralls is experiencing an outage and breaking CI, we'll need to wait on that: https://github.com/php-coveralls/php-coveralls/issues/353

**Pull request merged**
