### PR TITLE
Fix #392: pull:files multisite support

### LINKED ISSUE #392: Pulling files from a multisite always picks up the default directory in IDEs
Here's an example on Acquia CLI 1.4.0 when trying to copy files from the `another` site.

* Source path is: `/mnt/files/SITENAME.ENV/sites/another/files`
* Destination path is: `/home/ide/project/docroot/sites/default/`
* Destination path should be: `/home/ide/project/docroot/sites/another/`

I checked the `sites` directory on the Cloud server, and it does indeed have an `another` directory so there's no reason why we'd pull files under `default` instead of the right location.

```
SITENAMEENV@staging-1234:/var/www/html/SITENAME.ENV/docroot/sites$ ls -l
total 24
dr-xr-s--- 2 www-data SITENAME   39 Jan  6 05:27 another
dr-xr-s--- 2 www-data SITENAME  115 Jan  6 05:27 default
-r--r----- 1 www-data SITENAME  310 Jan  6 05:27 development.services.yml
-r--r----- 1 www-data SITENAME 5749 Jan  6 05:27 example.settings.local.php
-r--r----- 1 www-data SITENAME 2363 Jan  6 05:27 example.sites.php
-r--r----- 1 www-data SITENAME  515 Jan  6 05:27 README.txt
-r--r----- 1 www-data SITENAME 2428 Jan  6 05:27 sites.php
```

Here's the full verbose debug log:

```
    ✔ Pulling code from the Cloud Platform
    ⌛ Copying Drupal's public files from the Cloud Platform...
[notice] Command: 'ssh' 'SITENAME.ENV@SITENAMEENV.ssh.prod.acquia-sites.com' '-t' '-o StrictHostKeyChecking=no' '-o AddressFamily inet' '-o LogLevel=ERROR' 'ls' '/mnt/files/SITENAME.ENV/sites' [Exit: 0]
[debug] Command:  ls /mnt/files/SITENAME.ENV/sites [Exit: 0]
 Choose a site:
  [0] another
  [1] default
 > 0
receiving incremental file list
sent 46 bytes  received 3.58K bytes  2.42K bytes/sec
total size is 1.29M  speedup is 357.35
[notice] Command: 'rsync' '-rltDvPhe' 'ssh -o StrictHostKeyChecking=no' 'SITENAME.ENV@SITENAMEENV.ssh.prod.acquia-sites.com:/mnt/files/SITENAME.ENV/sites/another/files' '/home/ide/project/docroot/sites/default/' [
    ✔ Copying Drupal's public files from the Cloud Platform
```

This should be considered high because if people push files, then they're at risk of overwriting stuff.

### PR DESCRIPTION
**Pull request by danepowell**
Motivation
----------

Fixes #392 

Testing steps
---------

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `acli ckc`
3. Run `acli pull:files`
4. Choose a multisite and ensure that files are placed in the multisite directory rather than `default`

### CODE REVIEW

**Comment by anavarre** [comment]
It's on my list for today. Couldn't get to it yesterday, sorry.

**Comment by anavarre** [comment]
Still testing, but I cannot yet confirm it works as intended. Trying to see if the problem is with my testing or with the patch.

**Comment by anavarre** [comment]
When the files directory exists but doesn't correspond to a real Drupal site (e.g. site was deleted and files dir still remains on the Cloud Platform)**

```
 $ /tmp/cli/bin/acli pull:files -vvv
Acquia CLI version: @package_version@
[notice] Command: '/ide/drupal-setup.sh' [Exit: 0]
Using Cloud Application TEST

 Choose a Cloud Platform environment:
  [0] Dev, dev (vcs: master)
  [1] Stage, test (vcs: tags/2019-12-09.0)
 > 0

[debug] Using environment Dev 2005-b49l9c42-ee0c-142e-8305-1231390f2cc1
    ⌛ Copying Drupal's public files from the Cloud Platform...
[notice] Command: 'ssh' 'anavarre.dev@testdev.ssh.prod.acquia-sites.com' '-t' '-o StrictHostKeyChecking=no' '-o AddressFamily inet' '-o LogLevel=ERROR' 'ls' '/mnt/files/anavarre.dev/sites' [Exit: 0]
[debug] Command:  ls /mnt/files/anavarre.dev/sites [Exit: 0]
 Choose a site:
  [0] anavarre
  [1] default
  [2] another
  [3] another.org
  [4] another.org.anavarre
 > 2

receiving incremental file list


sent 140 bytes  received 52.77K bytes  35.27K bytes/sec
total size is 37.14M  speedup is 701.86

    ✔ Copying Drupal's public files from the Cloud Platform
````

The result here is nothing actually happens, but Acquia CLI still indicates all is well without actually doing anything.

**Review by anavarre — APPROVED** [review]

**Comment by danepowell** [comment]
Per convo in Slack and Aurelien's comment, there might be an underlying bug in how ACLI detects multisites, it should take into account DBs and not just look at directories on disk (this is arguable I suppose). Anyway, it's an existing issue and not a regression in this PR.

**Comment by anavarre** [comment]
Follow-up is #410

**Pull request merged**
