### PR TITLE
Unpatch symfony console

### PR DESCRIPTION
**Pull request by danepowell**
Symfony 5.2.6 contains the changes that we were previously applying via this patch.

### CODE REVIEW

**Comment by grasmash** [comment]
Weird, why would it work with the patch but not in the new version where the same exact changes are committed?

**Comment by danepowell** [comment]
I think there were other Symfony updates besides just our PRs. One of them appears to have broken Progress Bars.

**Comment by grasmash** [comment]
https://github.com/symfony/symfony/issues/40633

**Comment by grasmash** [comment]
A fix was merged upstream. Waiting for new console release.

**Comment by anavarre** [comment]
Fix is in https://github.com/symfony/symfony/releases/tag/v5.3.0-BETA1 - Do we want to try it out of wait for the final release?

**Comment by danepowell** [comment]
Considering that what blocked us on this PR was a breaking change in a stable patch release, I think the last think we should attempt is update to a beta 😄

**Comment by danepowell** [comment]
There's no need to keep a PR open for this, we'll wait for a new release and track via the internal ticket.

**Pull request closed without merging**
