### PR TITLE
Fix #228: PHP notice creating SSH key on ACSF

### LINKED ISSUE #228: PHP Notice:  Trying to get property 'sshUrl' of non-object in phar:///usr/local/bin/acli/src/Helpers/SshHelper.php on line 153
Ran into the below issue when testing RC6 on an ACSF test subscription. It also happens with RC1 so IDK under which conditions the error shows up because in non-ACE IDEs I have it working well.
```
ide:~$ ./acli.phar ide:wizard:ssh-key:create-upload
    ✔ Creating a local SSH key
    ✔ Uploading the local key to Acquia Cloud
    ✔ Adding the SSH key to local keychain
    ⠹ Waiting for the key to become available on Acquia Cloud web servers
PHP Notice:  Trying to get property 'sshUrl' of non-object in phar:///home/ide/acli.phar/src/Helpers/SshHelper.php on line 153
    ⣰ Waiting for the key to become available on Acquia Cloud web servers
PHP Notice:  Trying to get property 'sshUrl' of non-object in phar:///home/ide/acli.phar/src/Helpers/SshHelper.php on line 153
    ⡇ Waiting for the key to become available on Acquia Cloud web servers
(snip)
```

The key looks to be uploaded correctly though.

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #228  
--------

Motivation
----------
See #228 

Proposed changes
---------
Use the environment detector to detect a dev environment rather than looking for a hardcoded string ('dev').

Alternatives considered
---------
Copying the regex or hardcoded dev environment names from the environment detector... silly :smile: 

Testing steps
---------
Apply this PR as a patch, run `ide:wizard:ssh-key:create-upload` against an ACSF subscription, verify that notices are gone

@anavarre can you please test and verify this fixes the issue for you?

### CODE REVIEW

**Comment by anavarre** [comment]
I created a new IDE specifically to test this PR but unfortunately I ran into the same exact issue and even ended up running into a timeout (which I know is unrelated)

```
    ⡇ Waiting for the key to become available on Acquia Cloud web servers
PHP Notice:  Trying to get property 'sshUrl' of non-object in phar:///usr/local/bin/acli/src/Helpers/SshHelper.php on line 153
    ✔ Waiting for the key to become available on Acquia Cloud web servers
Timed out after 15 minutes!
```

**Review by anavarre — CHANGES_REQUESTED** [review]
Per my comment above.

**Comment by anavarre** [comment]
Any other idea how we could be solving this @danepowell ? I'd like to ship a new Acquia CLI version as soon as we can so the experience with ACSF is restored to normal operations.

**Comment by danepowell** [comment]
@anavarre did you make sure to run `composer install` after checking out this feature branch? I assume you were testing by checking out the ACLI feature branch in the IDE. It has new composer dependencies, if you don't `composer install` you'll get the old errors.

I just tested on an ACSF sub again and got no notices.

**Comment by anavarre** [comment]
After testing this more I cannot reproduce the issue. Let's assume I did something wrong the first time when I tested the fix. Looks good, ship it :smile:

**Pull request merged**
