### PR TITLE
Add validation for IDE labels

### PR DESCRIPTION
**Pull request by grasmash**
**Motivation**

Add validation to the label input when creating an IDE.

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `acli ckc`
3. Run `acli ide:create --label='1234!@#$'` and observe it fails
4. Run `acli ide:create` and manually input `!@#$`, observe it fails
5. Run `acli ide:create --label="Test This"` and observe it passes

**Merge requirements**
- [x] _Bug_, _enhancement_, or _breaking change_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by anavarre** [comment]
We still have an edge case here. We should not allow on spaces and likely only allow spaces between words, not at the beginning or end of the string.

Other than that things work:

```
$ ./bin/acli ide:create myapp --label='1234!@#$'

In IdeCreateCommand.php line 104:
                                                
  Please use only letters, numbers, and spaces  
                                                

ide:create [--label LABEL] [--] [<applicationUuid>]


                                                                                                                        
 [help] You can find Acquia CLI documentation at https://docs.acquia.com/acquia-cli/                                    
                                                                                                                        
        You can submit a support ticket at https://insight.acquia.com/support/tickets/new?product=p:cli                 
        Please re-run the command with the -vvv flag and include the full command output in                             
        your support ticket.                                                                                            
                                                                                                                        

$ ./bin/acli ide:create myapp

 Please enter a label for your Cloud IDE. Press enter to use default [My IDE]:
 > !@#$\r\n\t


                                                                                                                        
 [ERROR] Please use only letters, numbers, and spaces  
```

**Comment by anavarre** [comment]
Interesting one. I tried to create an IDE with only spaces and it eventually defaulted to the default name suggested. Unexpectedly smart

```
 Please enter a label for your Cloud IDE. Press enter to use default [My IDE]:
 >                     

    ✔ Creating your Cloud IDE
    ✔ Getting IDE information
    ✔ Waiting for the IDE to be ready. This can take up to 15 minutes...

Your IDE is ready!

Your IDE URL: https://myide.ide.ahdev.cloud
Your Drupal Site URL: https://myide.web.ahdev.cloud 
$ acli ide:list myapp
 ======================================================================= 
  IDEs                                                                   
 ======================================================================= 
  My IDE (my@email.com)                   
  IDE URL: https://myide.ide.ahdev.cloud  
  Web URL: https://myide.web.ahdev.cloud  
 ======================================================================= 
 ======================================================================= 
```

**Comment by grasmash** [comment]
Input is trimmed automatically by Symfony console. So, 
> We should not allow only spaces and likely only allow spaces between words, not at the beginning or end of the string.

This shouldn't be an issue?

**Review by anavarre — APPROVED** [review]
In which case I have nothing further to add.

**Pull request merged**
