### PR TITLE
Add make:docs command.

### PR DESCRIPTION
**Pull request by grasmash**
**Proposed changes**

Add `make:docs` command to output a description of all commands in markdown format.

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. Run `./bin/acli make:docs`

**Merge requirements**
- [x] _Bug_, _enhancement_, or _breaking change_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by anavarre** [comment]
I think it would be beneficial to comment somewhere in code the following is required:

```
brew install restview
./bin/acli make:docs > /tmp/acli.rst && restview /tmp/acli.rst
```

**Comment by grasmash** [comment]
> I think it would be beneficial to comment somewhere in code the following is required:
> 
> ```
> brew install restview
> ./bin/acli make:docs > /tmp/acli.rst && restview /tmp/acli.rst
> ```

Done!

**Comment by danepowell** [comment]
Sweet. Code looks good.

Can we rename it `self:make:docs`? The top-level namespace is getting so cluttered. See also CLI-679

**Comment by grasmash** [comment]
Yup.

**Review by danepowell — APPROVED** [review]

**Pull request merged**
