### PR TITLE
CLI-1031: Remove Lando overrides

### PR DESCRIPTION
**Pull request by danepowell**
Corresponding PR in Lando: https://github.com/lando/acquia/pull/56

### CODE REVIEW

**Comment by danepowell** [comment]
Closing until this is merged upstream

**Comment by reynoldsalec** [comment]
...this should get included in Lando v3.18.0, guessing that'll be released in the next week.

**Comment by anavarre** [comment]
Released in https://github.com/lando/acquia/releases/tag/v0.8.0 - Just waiting for v3.18.0 now.

**Comment by reynoldsalec** [comment]
@anavarre Lando v3.18.0 went out this last Friday, so you should be good to move forward!

**Pull request merged**
