### PR TITLE
Add user agent to ali ACLI requests to Cloud API

### PR DESCRIPTION
**Pull request by grasmash**
**Motivation**

Currently, only `api:*` commands are adding the `acli/*` user agent header. This makes _all_ commands include the header.

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `acli ckc`
3. Run `acli ide:list -vvv` and validate that user agent header is present.

**Merge requirements**
- [x] _Bug_, _enhancement_, or _breaking change_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by grasmash** [comment]
Not sure why tests are passing because I'm pretty sure this is actually broken:
```
./bin/acli ide:list -vvv
Acquia CLI version: @package_version@

Fatal error: Uncaught Error: Call to undefined method Acquia\Cli\CloudApi\ClientService::getApplication() in /Users/matthew.grasmick/Sites/acquia/cli/src/CloudApi/ClientService.php:35
Stack trace:
#0 /Users/matthew.grasmick/Sites/acquia/cli/src/Command/CommandBase.php(817): Acquia\Cli\CloudApi\ClientService->getClient()
#1 /Users/matthew.grasmick/Sites/acquia/cli/src/Command/CommandBase.php(795): Acquia\Cli\Command\CommandBase->doDetermineCloudApplication()
#2 /Users/matthew.grasmick/Sites/acquia/cli/src/Command/Ide/IdeListCommand.php(34): Acquia\Cli\Command\CommandBase->determineCloudApplication()
#3 /Users/matthew.grasmick/Sites/acquia/cli/vendor/symfony/console/Command/Command.php(256): Acquia\Cli\Command\Ide\IdeListCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/matthew.grasmick/Sites/acquia/cli/src/Command/CommandBase.php(411): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /Users/matthew.grasmick/Sites/acquia/cli/src/CloudApi/ClientService.php on line 35
```

**Comment by danepowell** [comment]
Passing the application via dependency injection fields a little wrong, but I think it works.

**Comment by danepowell** [comment]
SL query plus local debugging reveals that our custom user-agent is either not taking effect in the first place, or being clobbered by acquia-php-sdk: https://github.com/typhonius/acquia-php-sdk-v2/blob/cf100a54e9fef866f91abe586862a14209006a51/src/Connector/Client.php#L79

Maybe if we use modifyOptions like acquia-php-sdk it would work.

**Comment by typhonius** [comment]
https://github.com/typhonius/acquia_cli/blob/master/src/Cli/AcquiaCli.php#L53-L55

This should work :)

**Comment by danepowell** [comment]
@typhonius Thanks, that was what we were attempting in this PR but it didn't work. I think because acquia-php-sdk clobbers user agents that aren't arrays: https://github.com/typhonius/acquia-php-sdk-v2/blob/67afe42be076547cb90a5bcda13c3e146a408f09/src/Connector/Client.php#L89

Changing it from a string to array fixed it. I'm curious how this works in your Acquia CLI (does it?) but not in this PR.

**Review by danepowell — APPROVED** [review]

**Comment by danepowell** [comment]
@grasmash does this look good to you? You can't formally review it because you authored it, but you should check my commits.

**Comment by grasmash** [comment]
Looks good for now.

I wonder if we should submit a change upstream such that we are able to set headers with string values? It seems odd to me that an array is required.

**Comment by typhonius** [comment]
> @typhonius Thanks, that was what we were attempting in this PR but it didn't work. I think because acquia-php-sdk clobbers user agents that aren't arrays: https://github.com/typhonius/acquia-php-sdk-v2/blob/67afe42be076547cb90a5bcda13c3e146a408f09/src/Connector/Client.php#L89
> 
> Changing it from a string to array fixed it. I'm curious how this works in your Acquia CLI (does it?) but not in this PR.

I think Acquia Cli uses an array too if I'm not mistaken.

I think I made it an array so dependent libraries could add on as many headers as they wanted without fearing overwriting upstream libraries. The addOption method is quite forgiving in how it allows all sorts of options to be added in all around the codebase additively. It has benefits and drawbacks, but it's seemed to work to this point reasonably ok.

**Pull request merged**
