### PR TITLE
Fixes #641: Trigger custom scripts after acli pull commands

### LINKED ISSUE #641: Trigger custom scripts after `acli pull` commands
### Story

As a user, I'd like to run things like `drush db:update` automatically each time that I run `acli pull:db`.

### Implementation
I'd like to avoid introducing a new event system. However, I'm open to piggy-backing on an existing one, like Composer's. I propose that we check for the existence of a `post-acli-pull-db` script in composer.json, and if it exists, run `composer post-acli-pull-db`.

### PR DESCRIPTION
**Pull request by grasmash**
**Motivation**

Fixes #641

**Proposed changes**

After any ACLI command is run, ACLI will check `$(pwd)/composer.json` for a `post-acli-($command name)` script and execute it if present. E.g., `post-acli-db:pull`.

**Alternatives considered**

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. `cd` into a Drupal application directory containing a composer.json.
4. Add an entry to the `scripts` key in the composer.json:
```
        "post-acli-ide-list": [
            "echo \"Hello world\""
        ]
```
5. Run `[path to acli]/bin/acli ide-list -vvv`
6. Observe:
```
Executing composer script `post-acli-ide-list` defined in `/Users/matt.grasmick/Sites/projects/amad9/composer.json`
> echo "Hello world"
Hello world
[notice] Command: 'composer' 'run-script' 'post-acli-ide-list' [Exit: 0]
```

**Merge requirements**
- [x] _Bug_, _enhancement_, or _breaking change_ label applied
- [x] Manual testing by a reviewer

### CODE REVIEW

**Comment by mikemadison13** [comment]
I was able to test this locally and it seems to work!

**Comment by grasmash** [comment]
Cool. 

I have no idea how to write an automated test for this. Our tests don't seem to fire the ExceptionListener class.

**Comment by danepowell** [comment]
I'm onboard with the general idea of a hook system that can call out to Composer scripts, but I'm a little uncomfortable with this implementation. It's clever, but a little magical in some way that I don't like.

For instance... what if someone defines a post-pull-db script expecting it to run every time a db is imported (i.e. `pull:db`). They'd probably expect it to run on `pull` as well, right? But I don't think it will with the current implementation.

And I just imagine people demanding a more extensive hook system anyway at some point (with pre-, post-, and during hooks). Maybe it's better to consider that now.

If this implementation totally satisfies @mikemadison13 's use case, then I guess I'm cool with it. I appreciate that there's a ton of validation of the Composer scripts, so at least it's unlikely to cause problems.

**Comment by grasmash** [comment]
I considered the issue of pull not extending to pull:db, but that’s something that’s easily solved by the script implementation. Composer scripts can call one another. You could create a script and just ensure that it’s called in multiple hooks.

it doesn’t seem worth adding the complexity to our CLI when a very simple implementation change on the customer end would satisfy the requirements.

I would prefer to keep this as lightweight as possible, although I would be open to adding pre-hooks as well. That’s pretty straightforward And could probably use the same logic.

**Comment by mikemadison13** [comment]
i think for me to really say definitively the next step would be to start writing some scripts and doing side by side comparison of "if you run this blt command..." and then try to replicate it on this side using acli and whatever composer script. i'm sure there will be some deltas (good call out @danepowell !) but it's my hope we can work around them or evolve what ACLI does to adapt?

**Comment by grasmash** [comment]
This now supports "pre-acli*" and "post-acli*" hooks.

**Review by danepowell — APPROVED** [review]

**Pull request merged**
