### PR TITLE
Adding new command to get the used and un-used branches

### PR DESCRIPTION
**Pull request by joshirohit100**
```
acli app:used-unsed-branch-tags APPIDHERE

[INFO] List of used branches and tags: main-codestudio-build, tags/20211008-01, tags/2019-10-21



 [INFO] List of un-used branches: acquia-composer-update-codestudio-build, branch_2-codestudio-build,
        custom_test_job1-codestudio-build, develop, develop-build, develop-build-codestudio-build, develop-new, master,
        merge_check-codestudio-build, rohit_test_1-codestudio-build, rohit_test_2-codestudio-build,
        test2-codestudio-build, test_1-codestudio-build, test_local-codestudio-build, yaml_validate-codestudio-build



 [INFO] List of un-used tags: tags/12-03-2020-1, tags/12-03-2020-2, tags/12-03-2020-3, tags/14-03-2020-1,
        tags/14-03-2020-2, tags/14-03-2020-3, tags/18-01-2020, tags/20-03-2020-1, tags/2019-06-27, tags/2019-06-27.0,
        tags/2019-06-28, tags/2019-06-28-I, tags/2019-06-30, tags/2019-07-03, tags/2019-07-03-1, tags/2019-07-11,
        tags/2019-07-11-a, tags/2019-11-11, tags/2019-11-11-b, tags/2020-18-01, tags/20201031, tags/20201031-02,
        tags/22-02-2020.1, tags/22-02-2020.2, tags/25-03-2020-1, tags/pre-import-2019-06-21, tags/tag/2019-06-28
```

### CODE REVIEW

**Comment by grasmash** [comment]
Seems like it would be better to generalize this to a command that shows all branches for an app, sorted by whether it's deployed.

**Comment by joshirohit100** [comment]
@anavarre
Example - In my current project we create a feature branch and continue v development on that feature branch and deploy that on some environment of an application. Once feature development is completed, we merge the feature branch in mainstream branch (dev, stage, main). 

As we work on many ^^ in parallel, many new branches created which deployed somewhere at sometime but not required after merging in dev

So in order to do the cleanup of the branches, we first check which are not deployed and remove them. 

This command can be used in determining whether branch/tag is in use Or not. 

Also now with code studio, all branches and tags are created for the merge request in main repo, and each branch pushed to cloud, cloud is cluttered with so many unused branches. So for cleanup, this can be used as well

**Comment by anavarre** [comment]
@joshirohit100 I see. But then you don't care so much about listing branches but deleting them (those unused), correct? So wouldn't the command be rather something like `app:delete:unused [--tags|--branches]`?

**Comment by joshirohit100** [comment]
@anavarre yes! that also I was thinking to ask user to delete (once show the used/unsed info) but then in acquia php-sdk `AcquiaCloudApi\Endpoints\Applications` I could only find deleteTag() and nothing for branch delete

**Comment by danepowell** [comment]
I'm fine with this in principle but I find the current name (used-unused) pretty confusing. As Matt suggested, I think it needs to be a more general command to list branches and their status (if used, where?).

It also needs to have automated tests and all tests passing, and ideally any mutations squashed.

I'm going to close for now to get it out of the queue but please don't take that as an indication that it's not appreciated! It just needs to be cleaned up and I'm guessing that's easier to do in a new PR.

**Pull request closed without merging**
