### PR TITLE
CLI-825: Realm support for environment aliases

### PR DESCRIPTION
**Pull request by danepowell**
**Motivation**

```
$ acli api:environments:ssl gardens-prod:c[snip]i.prod

In CacheItem.php line 159:

  Cache key "gardens-prod:c[snip]i.prod" contains reserved characters "{}()/\@:".
api:environments:ssl-settings-find <environmentId>
```

**Proposed changes**

Abstract cache to reduce code duplication so we don't overlook this again

**Testing steps**

1. Follow the [contribution guide](https://github.com/acquia/cli/blob/master/CONTRIBUTING.md#building-and-testing) to set up your development environment.
2. Clear the kernel cache to pick up new and changed commands: `./bin/acli ckc`
3. Try using an environment alias with realm again. Note that `gardens` is not

### CODE REVIEW

**Comment by danepowell** [comment]
@eporama can you please help test so we can get this released quickly? Here's a dev phar, let @anavarre or I know if you need any help: https://transfer.sh/sYHH9O/acli.phar

Note that this only fixes the cache key error, see CLI-825 for details.

**Comment by anavarre** [comment]
If this is the expected outcome, this is working now.

```
❯ ./acli.phar api:environments:ssl gardens:c[snip]i.prod

In CommandBase.php line 1771:

  {environmentId} must be a valid UUID or site alias.


api:environments:ssl-settings-find <environmentId>



 [help] environmentId can also be a site alias. E.g. myapp.dev.
        Run acli remote:aliases:list to see a list of all available aliases.

        You can find Acquia CLI documentation at https://docs.acquia.com/acquia-cli/

        You can submit a support ticket at https://support-acquia.force.com/s/contactsupport
        Please re-run the command with the -vvv flag and include the full command output in
        your support ticket.
```

**Comment by danepowell** [comment]
Ah right, that is an expected error because `gardens` is not a valid realm for that site. I think `gardens-prod` worked when I checked.

**Review by anavarre — APPROVED** [review]
That worked.

```
❯ ./acli.phar api:environments:ssl gardens-prod:c[snip]i.prod | head -n2
{
    "balancer": null,
```

**Review by eporama — APPROVED** [review]

**Pull request merged**
