### PR TITLE
New command: `app:new:from:drupal7`

### PR DESCRIPTION
**Pull request by wimleers**
**Motivation**
ACLI already has a `app:new:local` command that spins up a brand new Drupal project.

Wouldn't it be great if it also helped you spin up a new Drupal 9+ project that helps migrating from Drupal 7?

**Proposed changes**
Introduce `acli app:new:from:drupal7`.

All code has been battle-hardened over years of use in production on Acquia Cloud. Please check the commits in sequence, because I designed them to tell a gradual story:
1. code to inspect a Drupal 7 site's installed modules
2. introduce the new ACLI command
3. add unit tests
4. add integration tests

Until the full set of _recommendations_ is released, this will use only a minimal set of recommendations, primarily consisting of some Drupal 7 → 9 migration recommendations for Acquia modules.

This is a necessary step in the way of open sourcing https://www.acquia.com/products/drupal-cloud/acquia-migrate-accelerate.

**Alternatives considered**
N/A

**Testing steps**
Point it at a Drupal 7 site and observe that it generates a valid `composer.json` that results in an installable Drupal 9+ site. See the integration tests for various sample Drupal 7 sites at `tests/phpunit/src/Commands/App/NewFromDrupal7CommandTest.php`, with fixtures at `tests/fixtures/drupal7`.

### CODE REVIEW

**Comment by anavarre** [comment]
Hey Wim! Thanks for your contribution. @danepowell is out for ~2 weeks so expect radio silence for a little while. Making visible to @mikemadison13 for AMA efforts.

**Comment by wimleers** [comment]
> Hey Wim! Thanks for your contribution. @danepowell is out for ~2 weeks so expect radio silence for a little while. Making visible to @mikemadison13 for AMA efforts.

Yep, I'm aware 😊

**Comment by wimleers** [comment]
At least in 987ce00, there were some genuine failures:
```
1)                                                                     
         Acquia\Cli\Tests\Commands\App\From\AbandonmentRecommendationTest::testVersionCon
         straint                                                                
         "@covers getVersionConstraint" is invalid      
```

Fixed in 9a0814b.

Rooting for full green again after the weird auto-canceling CI jobs! 🤞

**Comment by wimleers** [comment]
Aha, looks like there was a failure on Windows too. `getLocation()` only works on UNIX-style paths today:
```
Script @unit-parallel was called via unit
1) Acquia\Cli\Tests\Commands\App\NewFromDrupal7CommandTest::testNewFromDrupal7Command with data set "training.acquia.com" ('D:\a\cli\cli/tests/fixtures/d...s.json', 'D:\a\cli\cli/config/from_d7_r...s.json', 'D:\a\cli\cli/tests/fixtures/d...d.json')
Script @unit was called via test
TypeError: Acquia\Cli\Command\App\NewFromDrupal7Command::getLocation(): Return value must be of type string, bool returned
```
 Attempted a fix.

**Comment by wimleers** [comment]
🥳 Green!

For fun, I also checked the mutation testing output, which I've never before seen. It's pretty cool, and it shows that the tests catch most things:
```
279 mutations were generated:
     216 mutants were killed
       0 mutants were configured to be ignored
       0 mutants were not covered by tests
      62 covered mutants were not detected
       0 errors were encountered
       0 syntax errors were encountered
       1 time outs were encountered
       0 mutants required more time than configured

Metrics:
         Mutation Score Indicator (MSI): 77%
         Mutation Code Coverage: 100%
         Covered Code MSI: 77%
```
Most of these are for the untestable "inspect a live Drupal 7 site" code path. But not all. One of them is pretty silly and is only due to a limitation in PHP <8:
```
Warning: Escaped Mutant for Mutator "DecrementInteger":

--- Original
+++ New
@@ @@
     {
         assert(is_resource($resource));
         $json = stream_get_contents($resource);
-        return json_decode($json, TRUE, 512, JSON_OBJECT_AS_ARRAY | JSON_THROW_ON_ERROR);
+        return json_decode($json, TRUE, 511, JSON_OBJECT_AS_ARRAY | JSON_THROW_ON_ERROR);
     }
 }


Warning: Escaped Mutant for Mutator "IncrementInteger":

--- Original
+++ New
@@ @@
     {
         assert(is_resource($resource));
         $json = stream_get_contents($resource);
-        return json_decode($json, TRUE, 512, JSON_OBJECT_AS_ARRAY | JSON_THROW_ON_ERROR);
+        return json_decode($json, TRUE, 513, JSON_OBJECT_AS_ARRAY | JSON_THROW_ON_ERROR);
     }
 }
```

Just switching to [PHP >=8's _named arguments_](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments) fixes this!

**Comment by wimleers** [comment]
```
3646 mutations were generated:
    1364 mutants were killed
       0 mutants were configured to be ignored
       0 mutants were not covered by tests
     772 covered mutants were not detected
      69 errors were encountered
       0 syntax errors were encountered
      20 time outs were encountered
    1421 mutants required more time than configured

Metrics:
         Mutation Score Indicator (MSI): 65%
         Mutation Code Coverage: 100%
         Covered Code MSI: 65%
```

☝️ this PR means a net improvement to the mutation score 😊 (Would be cool to have a target to not regress against this too?)

**Comment by wimleers** [comment]
a9c042e fixes a bug that I found while updating an integration test of a private repo to rely on the new ACLI command being introduced here.

That integration test _does_ point to a real, live Drupal 7 site. It crashed like so:
```
php ./bin/acli app:new:from:drupal7 --drupal7-directory $D7_DIR --recommendations "$RECOMMENDATIONS_DIR/recommendations.json" --directory /tmp/build
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.
 Would you like to share anonymous performance usage and data? (yes/no) [yes]:
 > Awesome! Thank you for helping!

 [ERROR] The given --drupal7-uri value does not correspond to an installed sites
         directory and a sites.php file could not be located.        
```

**Comment by danepowell** [comment]
@wimleers this looks good to me, but it's still in draft state. Is this ready for review?

**Comment by danepowell** [comment]
Adam mentioned that we need to wait for approval on this.

**Comment by wimleers** [comment]
There's absolutely no reason left that it's in draft state 😅 I should've marked this as ready for review ever since https://github.com/acquia/cli/pull/1543#issuecomment-1597474021 — sorry!

**Comment by wimleers** [comment]
Still green, but:
```
Failing after 1s — 91.61% of diff hit (target 91.77%)
```
[Back in June](https://github.com/acquia/cli/pull/1543#issuecomment-1597419598), the target was `91.56%` 😬 I hope that won't hold this up? 😇

**Pull request merged**
