### PR TITLE
Fixes #522: ACLI fails to push the database.

### LINKED ISSUE #522: ACLI fails to push the database
Here's me trying to push my DB by building from source. Note, this is confirming a customer issue that was reported.

```
$ /tmp/cli/bin/acli push:db -vvv
Acquia CLI version: @package_version@
Using Cloud Application myapp

 Choose a Cloud Platform environment [Dev, dev (vcs: pipelines-build-master)]:
  [0] Dev, dev (vcs: pipelines-build-master)
  [1] test, ode28 (vcs: pipelines-build-master)
  [2] Stage, test (vcs: tags/2020-10-19)
 > 1

[debug] Using environment test 144528-0e737068-196c-4b7c-8b6e-3fdf0561b428
 Choose a database [myapp (default)]:
  [0] myapp (default)
  [1] drupal9
 > 0

 Overwrite the myapp database on ode28 with a copy of the database from the current machine? (yes/no) [yes]:
 > yes

    ⌛ Creating local database dump...

[debug] Dumping MySQL database to /tmp/acli-mysql-dump-drupal.sql.gz on this machine
    ✔ Creating local database dump
    ⌛ Uploading database dump to remote machine...

[debug] Uploading database dump to /mnt/tmp/93k230o43da74b5983cef89fd8c11978/acli-mysql-dump-drupal.sql.gz on remote machine
rsync: change_dir#3 "/mnt/tmp/93k230o43da74b5983cef89fd8c11978" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.1]
[notice] Command: 'rsync' '-tDvPhe' 'ssh -o StrictHostKeyChecking=no' '/tmp/acli-mysql-dump-drupal.sql.gz' 'myapp.ode28@myapp.ssh.prod.acquia-sites.com:/mnt/tmp/93k230o43da74b5983cef89fd8c11978/acli-mysql-dump-drupal.sql.gz' [Exit: 3]

In PushDatabaseCommand.php line 117:
                                             
  [Acquia\Cli\Exception\AcquiaCliException]  
  Could not upload local database dump:      
                                             

Exception trace:
  at /tmp/cli/src/Command/Push/PushDatabaseCommand.php:117
 Acquia\Cli\Command\Push\PushDatabaseCommand->uploadDatabaseDump() at /tmp/cli/src/Command/Push/PushDatabaseCommand.php:58
 Acquia\Cli\Command\Push\PushDatabaseCommand->execute() at /tmp/cli/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /tmp/cli/src/Command/CommandBase.php:405
 Acquia\Cli\Command\CommandBase->run() at /tmp/cli/vendor/symfony/console/Application.php:989
 Symfony\Component\Console\Application->doRunCommand() at /tmp/cli/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /tmp/cli/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /tmp/cli/bin/acli:87

push:database [<environmentId>]


                                                                                                                        
 [help] You can find Acquia CLI documentation at https://docs.acquia.com/acquia-cli/                                    
                                                                                                                        
        You can submit a support ticket at https://insight.acquia.com/support/tickets/new?product=p:cli                 
                                                                                                                      
```

### PR DESCRIPTION
**Pull request by grasmash**
Fix #522

Correctly identify the tmp directory on ODEs.

### CODE REVIEW

**Review by danepowell — APPROVED** [review]

**Comment by danepowell** [comment]
@anavarre know you're busy, do you want to test that this fixes your issue, or should we merge without you?

**Comment by anavarre** [comment]
Happy to try it out now. Will report back shortly.

**Comment by anavarre** [comment]
I cannot make this work (I've built from source):

```
 Overwrite the myapp database on ode28 with a copy of the database from the current machine? (yes/no) [yes]:
 > y

    ✔ Creating local database dump
    ⠛ Uploading database dump to remote machine...
        rsync: change_dir#3 "/mnt/tmp/83f230c43dk74b5983ckf89fd8c11978" failed: No such file or directory (2)

In PushDatabaseCommand.php line 117:
                                         
  Could not upload local database dump:  
                                         

push:database [<environmentId>]
```

**Comment by grasmash** [comment]
That looks an awful lot like the old code. Either you are using the Ryan branch, or my changes or somehow not affecting your code execution.

**Comment by danepowell** [comment]
Here's the built phar for this PR if you want to cross-check: https://transfer.sh/DZCdH/acli.phar

**Review by anavarre — APPROVED** [review]
```
 Overwrite the myapp database on ode28 with a copy of the database from the current machine? (yes/no) [yes]:
 > yes

    ⌛ Creating local database dump...

[debug] Dumping MySQL database to /tmp/acli-mysql-dump-drupal.sql.gz on this machine
    ✔ Creating local database dump
    ⌛ Uploading database dump to remote machine...

[debug] Uploading database dump to /mnt/tmp/myapp.ode28/acli-mysql-dump-drupal.sql.gz on remote machine
acli-mysql-dump-drupal.sql.gz
          1.12M 100%  206.71MB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 1.12M bytes  received 35 bytes  2.23M bytes/sec
total size is 1.12M  speedup is 1.00
    ✔ Uploading database dump to remote machine
    ⌛ Importing database dump into MySQL on remote machine...

[debug] Importing /mnt/tmp/myapp.ode28/acli-mysql-dump-drupal.sql.gz to MySQL on remote machine
1.06MiB [ 120KiB/s]
Connection to myappode28.ssh.prod.acquia-sites.com closed.
[notice] Command: 'ssh' 'myapp.ode28@myappode28.ssh.prod.acquia-sites.com' '-t' '-o StrictHostKeyChecking=no' '-o AddressFamily inet' '-o LogLevel=ERROR' 'pv /mnt/tmp/myapp.ode28/acli-mysql-dump-drupal.sql.gz --bytes --rate | gunzip | MYSQL_PWD=pol5h91eAx+FzNVP+E0p9Z55ikaENWp0hDYRg mysql --host=db-94f230c43da74b5983cef89fd8k11971.cdb.database.services.acquia.io --user=uzlkjlk457QngukGDA 94f230c43da74b5983cef89fd8k11971' [Exit: 0]
    ✔ Importing database dump into MySQL on remote machine
```

**Pull request merged**
